/**
 * Budget Estimate Document Generator
 *
 * Converts a budget artifact (Stage 3) into a formatted Word document.
 */
import { Paragraph, Table } from "docx";
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  labeledField,
  simpleTable,
  keyValueTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateBudget(data: any): Promise<Buffer> {
  const contingency = data.contingency ?? {};

  const content: (Paragraph | Table)[] = [
    title("Budget Estimate"),
    subtitle(s(data.projectName)),
    spacer(),

    labeledField("Currency", s(data.currency)),
    spacer(),
  ];

  // Category breakdowns
  for (const cat of a<any>(data.categories)) {
    content.push(heading1(s(cat?.category)));
    content.push(
      simpleTable(
        ["Item", "Amount", "Notes"],
        a<any>(cat?.lineItems).map((li: any) => [s(li?.item), s(li?.amount), s(li?.notes)]),
        [35, 20, 45]
      )
    );
    content.push(labeledField("Subtotal", s(cat?.subtotal)));
    content.push(spacer());
  }

  // Summary
  content.push(heading1("Budget Summary"));
  content.push(
    keyValueTable([
      { key: "Contingency", value: `${s(contingency.percentage)} (${s(contingency.amount)})` },
      { key: "Total Budget", value: s(data.totalBudget) },
    ])
  );

  content.push(divider());
  content.push(bodyText("This document was generated by BriefKit.", { italic: true }));

  const doc = createDocument(content);
  return Buffer.from(await Packer.toBuffer(doc));
}
