/**
 * Budget Estimate Document Generator
 *
 * Converts a budget artifact (Stage 3) into a formatted Word document.
 */
import { Paragraph, Table } from "docx";
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  labeledField,
  simpleTable,
  keyValueTable,
  spacer,
  divider,
} from "./base-generator";

interface BudgetData {
  projectName: string;
  currency: string;
  categories: {
    category: string;
    lineItems: { item: string; amount: string; notes: string }[];
    subtotal: string;
  }[];
  contingency: { percentage: string; amount: string };
  totalBudget: string;
}

export async function generateBudget(data: BudgetData): Promise<Buffer> {
  const content: (Paragraph | Table)[] = [
    title("Budget Estimate"),
    subtitle(data.projectName),
    spacer(),

    labeledField("Currency", data.currency),
    spacer(),
  ];

  // Category breakdowns
  for (const cat of data.categories) {
    content.push(heading1(cat.category));
    content.push(
      simpleTable(
        ["Item", "Amount", "Notes"],
        cat.lineItems.map((li) => [li.item, li.amount, li.notes]),
        [35, 20, 45]
      )
    );
    content.push(labeledField("Subtotal", cat.subtotal));
    content.push(spacer());
  }

  // Summary
  content.push(heading1("Budget Summary"));
  content.push(
    keyValueTable([
      { key: "Contingency", value: `${data.contingency.percentage} (${data.contingency.amount})` },
      { key: "Total Budget", value: data.totalBudget },
    ])
  );

  content.push(divider());
  content.push(bodyText("This document was generated by Brief-to-Project.", { italic: true }));

  const doc = createDocument(content);
  return Buffer.from(await Packer.toBuffer(doc));
}
