/**
 * Business Case Document Generator
 *
 * Converts a business-case artifact (Stage 2) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateBusinessCase(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Business Case"),
    subtitle(s(data.projectName)),
    spacer(),

    // ── Executive Summary ──
    heading1("Executive Summary"),
    bodyText(s(data.executiveSummary)),
    spacer(),

    // ── Problem Statement ──
    heading1("Problem Statement"),
    bodyText(s(data.problemStatement)),
    spacer(),

    // ── Proposed Solution ──
    heading1("Proposed Solution"),
    bodyText(s(data.proposedSolution)),
    spacer(),

    // ── Benefits ──
    heading1("Expected Benefits"),
    simpleTable(
      ["Benefit", "Type", "Estimated Value"],
      a(data.benefits).map((b: any) => [s(b?.benefit), s(b?.type), s(b?.estimatedValue)]),
      [45, 20, 35]
    ),
    spacer(),

    // ── Costs ──
    heading1("Estimated Costs"),
    simpleTable(
      ["Category", "Amount", "Notes"],
      a(data.costs).map((c: any) => [s(c?.category), s(c?.amount), s(c?.notes)]),
      [30, 25, 45]
    ),
    spacer(),

    // ── ROI ──
    heading1("Return on Investment"),
    labeledField("Projected ROI", s(data.roi)),
    spacer(),

    // ── Risks ──
    heading1("Key Risks"),
    ...a(data.risks).map((r: any) => bulletItem(s(r))),
    spacer(),

    // ── Recommendation ──
    heading1("Recommendation"),
    bodyText(s(data.recommendation)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
