/**
 * Change Management Plan Document Generator
 *
 * Converts a change-management-plan artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateChangeManagementPlan(data: any): Promise<Buffer> {
  const changeProcess = data.changeProcess ?? {};

  const doc = createDocument([
    title("Change Management Plan"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Change Request Process"),
    heading2("Submission Method"),
    bodyText(s(changeProcess.submissionMethod)),

    heading2("Required Information"),
    ...a(changeProcess.requiredInformation).map((r: any) => bulletItem(s(r))),

    heading2("Impact Assessment"),
    bodyText(s(changeProcess.impactAssessment)),
    spacer(),

    heading1("Approval Thresholds"),
    simpleTable(
      ["Change Type", "Approver", "Process"],
      a(data.approvalThresholds).map((threshold: any) => [s(threshold?.changeType), s(threshold?.approver), s(threshold?.process)]),
      [30, 30, 40]
    ),
    spacer(),

    heading1("Change Log Fields"),
    ...a(data.changeLogFields).map((f: any) => bulletItem(s(f))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
