/**
 * Change Management Plan Document Generator
 *
 * Converts a change-management-plan artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface ChangeManagementPlanData {
  projectName: string;
  changeProcess: {
    submissionMethod: string;
    requiredInformation: string[];
    impactAssessment: string;
  };
  approvalThresholds: {
    changeType: string;
    approver: string;
    process: string;
  }[];
  changeLogFields: string[];
}

export async function generateChangeManagementPlan(data: ChangeManagementPlanData): Promise<Buffer> {
  const doc = createDocument([
    title("Change Management Plan"),
    subtitle(data.projectName),
    spacer(),

    heading1("Change Request Process"),
    heading2("Submission Method"),
    bodyText(data.changeProcess.submissionMethod),

    heading2("Required Information"),
    ...data.changeProcess.requiredInformation.map((r) => bulletItem(r)),

    heading2("Impact Assessment"),
    bodyText(data.changeProcess.impactAssessment),
    spacer(),

    heading1("Approval Thresholds"),
    simpleTable(
      ["Change Type", "Approver", "Process"],
      data.approvalThresholds.map((a) => [a.changeType, a.approver, a.process]),
      [30, 30, 40]
    ),
    spacer(),

    heading1("Change Log Fields"),
    ...data.changeLogFields.map((f) => bulletItem(f)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
