/**
 * Project Charter Document Generator
 *
 * Converts a charter artifact (Stage 2) into a formatted Word document.
 * This is the most comprehensive document — multiple sections with tables.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface CharterData {
  projectName: string;
  projectSponsor: string;
  projectManager: string;
  date: string;
  executiveSummary: string;
  businessCase: {
    problemStatement: string;
    strategicAlignment: string;
    expectedBenefits: string[];
    costBenefitSummary: string;
  };
  objectives: { objective: string; measure: string; target: string }[];
  scope: {
    inScope: string[];
    outOfScope: string[];
    assumptions: string[];
    constraints: string[];
  };
  milestones: { milestone: string; targetDate: string }[];
  budget: { estimated: string; contingency: string; fundingSource: string };
  risks: { risk: string; impact: string; mitigation: string }[];
  approvers: { name: string; role: string }[];
}

export async function generateCharter(data: CharterData): Promise<Buffer> {
  const doc = createDocument([
    // ── Title Block ──
    title("Project Charter"),
    subtitle(data.projectName),
    subtitle(`${data.date}`),
    spacer(),

    // ── Project Info ──
    keyValueTable([
      { key: "Project Name", value: data.projectName },
      { key: "Project Sponsor", value: data.projectSponsor },
      { key: "Project Manager", value: data.projectManager },
      { key: "Date", value: data.date },
    ]),
    spacer(),

    // ── Executive Summary ──
    heading1("Executive Summary"),
    bodyText(data.executiveSummary),
    spacer(),

    // ── Business Case ──
    heading1("Business Case"),
    heading2("Problem Statement"),
    bodyText(data.businessCase.problemStatement),

    heading2("Strategic Alignment"),
    bodyText(data.businessCase.strategicAlignment),

    heading2("Expected Benefits"),
    ...data.businessCase.expectedBenefits.map((b) => bulletItem(b)),

    heading2("Cost-Benefit Summary"),
    bodyText(data.businessCase.costBenefitSummary),
    spacer(),

    // ── Objectives ──
    heading1("Project Objectives"),
    simpleTable(
      ["Objective", "Measure", "Target"],
      data.objectives.map((o) => [o.objective, o.measure, o.target]),
      [40, 30, 30]
    ),
    spacer(),

    // ── Scope ──
    heading1("Scope"),
    heading2("In Scope"),
    ...data.scope.inScope.map((item) => bulletItem(item)),

    heading2("Out of Scope"),
    ...data.scope.outOfScope.map((item) => bulletItem(item)),

    heading2("Assumptions"),
    ...data.scope.assumptions.map((item) => bulletItem(item)),

    heading2("Constraints"),
    ...data.scope.constraints.map((item) => bulletItem(item)),
    spacer(),

    // ── Milestones ──
    heading1("Key Milestones"),
    simpleTable(
      ["Milestone", "Target Date"],
      data.milestones.map((m) => [m.milestone, m.targetDate]),
      [60, 40]
    ),
    spacer(),

    // ── Budget ──
    heading1("Budget"),
    keyValueTable([
      { key: "Estimated Budget", value: data.budget.estimated },
      { key: "Contingency", value: data.budget.contingency },
      { key: "Funding Source", value: data.budget.fundingSource },
    ]),
    spacer(),

    // ── Risks ──
    heading1("Initial Risks"),
    simpleTable(
      ["Risk", "Impact", "Mitigation"],
      data.risks.map((r) => [r.risk, r.impact, r.mitigation]),
      [35, 25, 40]
    ),
    spacer(),

    // ── Approvals ──
    heading1("Approvals"),
    simpleTable(
      ["Name", "Role", "Signature", "Date"],
      data.approvers.map((a) => [a.name, a.role, "", ""]),
      [30, 30, 25, 15]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
