/**
 * Project Charter Document Generator
 *
 * Converts a charter artifact (Stage 2) into a formatted Word document.
 * This is the most comprehensive document — multiple sections with tables.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateCharter(data: any): Promise<Buffer> {
  const businessCase = data.businessCase ?? {};
  const scope = data.scope ?? {};
  const budget = data.budget ?? {};

  const doc = createDocument([
    // ── Title Block ──
    title("Project Charter"),
    subtitle(s(data.projectName)),
    subtitle(`${s(data.date)}`),
    spacer(),

    // ── Project Info ──
    keyValueTable([
      { key: "Project Name", value: s(data.projectName) },
      { key: "Project Sponsor", value: s(data.projectSponsor) },
      { key: "Project Manager", value: s(data.projectManager) },
      { key: "Date", value: s(data.date) },
    ]),
    spacer(),

    // ── Executive Summary ──
    heading1("Executive Summary"),
    bodyText(s(data.executiveSummary)),
    spacer(),

    // ── Business Case ──
    heading1("Business Case"),
    heading2("Problem Statement"),
    bodyText(s(businessCase.problemStatement)),

    heading2("Strategic Alignment"),
    bodyText(s(businessCase.strategicAlignment)),

    heading2("Expected Benefits"),
    ...a(businessCase.expectedBenefits).map((b: any) => bulletItem(s(b))),

    heading2("Cost-Benefit Summary"),
    bodyText(s(businessCase.costBenefitSummary)),
    spacer(),

    // ── Objectives ──
    heading1("Project Objectives"),
    simpleTable(
      ["Objective", "Measure", "Target"],
      a(data.objectives).map((o: any) => [s(o?.objective), s(o?.measure), s(o?.target)]),
      [40, 30, 30]
    ),
    spacer(),

    // ── Scope ──
    heading1("Scope"),
    heading2("In Scope"),
    ...a(scope.inScope).map((item: any) => bulletItem(s(item))),

    heading2("Out of Scope"),
    ...a(scope.outOfScope).map((item: any) => bulletItem(s(item))),

    heading2("Assumptions"),
    ...a(scope.assumptions).map((item: any) => bulletItem(s(item))),

    heading2("Constraints"),
    ...a(scope.constraints).map((item: any) => bulletItem(s(item))),
    spacer(),

    // ── Milestones ──
    heading1("Key Milestones"),
    simpleTable(
      ["Milestone", "Target Date"],
      a(data.milestones).map((m: any) => [s(m?.milestone), s(m?.targetDate)]),
      [60, 40]
    ),
    spacer(),

    // ── Budget ──
    heading1("Budget"),
    keyValueTable([
      { key: "Estimated Budget", value: s(budget.estimated) },
      { key: "Contingency", value: s(budget.contingency) },
      { key: "Funding Source", value: s(budget.fundingSource) },
    ]),
    spacer(),

    // ── Risks ──
    heading1("Initial Risks"),
    simpleTable(
      ["Risk", "Impact", "Mitigation"],
      a(data.risks).map((r: any) => [s(r?.risk), s(r?.impact), s(r?.mitigation)]),
      [35, 25, 40]
    ),
    spacer(),

    // ── Approvals ──
    heading1("Approvals"),
    simpleTable(
      ["Name", "Role", "Signature", "Date"],
      a(data.approvers).map((approver: any) => [s(approver?.name), s(approver?.role), "", ""]),
      [30, 30, 25, 15]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
