/**
 * Communication Plan Document Generator
 *
 * Converts a communication-plan artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface CommunicationPlanData {
  projectName: string;
  communications: {
    audience: string;
    information: string;
    frequency: string;
    channel: string;
    owner: string;
  }[];
}

export async function generateCommunicationPlan(data: CommunicationPlanData): Promise<Buffer> {
  const doc = createDocument([
    title("Communication Plan"),
    subtitle(data.projectName),
    spacer(),

    heading1("Communication Schedule"),
    simpleTable(
      ["Audience", "Information", "Frequency", "Channel", "Owner"],
      data.communications.map((c) => [
        c.audience,
        c.information,
        c.frequency,
        c.channel,
        c.owner,
      ]),
      [18, 30, 14, 18, 20]
    ),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
