/**
 * Communication Plan Document Generator
 *
 * Converts a communication-plan artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateCommunicationPlan(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Communication Plan"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Communication Schedule"),
    simpleTable(
      ["Audience", "Information", "Frequency", "Channel", "Owner"],
      a(data.communications).map((c: any) => [
        s(c?.audience),
        s(c?.information),
        s(c?.frequency),
        s(c?.channel),
        s(c?.owner),
      ]),
      [18, 30, 14, 18, 20]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
