/**
 * Documentation Completeness Report Generator
 *
 * Converts a completeness-report artifact (Stage 6) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  labeledField,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateCompletenessReport(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Documentation Completeness Report"),
    subtitle(s(data.projectName)),
    subtitle(`Generated: ${s(data.generatedDate)}`),
    spacer(),

    heading1("Overall Status"),
    labeledField("Status", s(data.overallStatus)),
    spacer(),

    // ── Artifact Inventory ──
    heading1("Artifact Inventory"),
    simpleTable(
      ["Artifact", "Stage", "Status", "Notes"],
      a(data.artifacts).map((artifact: any) => [s(artifact?.title), String(artifact?.stage ?? ""), s(artifact?.status), s(artifact?.notes)]),
      [35, 10, 15, 40]
    ),
    spacer(),

    // ── Consistency Checks ──
    heading1("Consistency Checks"),
    simpleTable(
      ["Check", "Result", "Notes"],
      a(data.consistencyChecks).map((c: any) => [s(c?.check), s(c?.result), s(c?.notes)]),
      [35, 15, 50]
    ),
    spacer(),

    // ── Recommendations ──
    heading1("Recommendations"),
    ...a(data.recommendations).map((r: any) => bulletItem(s(r))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
