/**
 * Documentation Completeness Report Generator
 *
 * Converts a completeness-report artifact (Stage 6) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  labeledField,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface CompletenessReportData {
  projectName: string;
  generatedDate: string;
  artifacts: {
    type: string;
    title: string;
    stage: number;
    status: string;
    notes: string;
  }[];
  consistencyChecks: {
    check: string;
    result: string;
    notes: string;
  }[];
  recommendations: string[];
  overallStatus: string;
}

export async function generateCompletenessReport(data: CompletenessReportData): Promise<Buffer> {
  const doc = createDocument([
    title("Documentation Completeness Report"),
    subtitle(data.projectName),
    subtitle(`Generated: ${data.generatedDate}`),
    spacer(),

    heading1("Overall Status"),
    labeledField("Status", data.overallStatus),
    spacer(),

    // ── Artifact Inventory ──
    heading1("Artifact Inventory"),
    simpleTable(
      ["Artifact", "Stage", "Status", "Notes"],
      data.artifacts.map((a) => [a.title, String(a.stage), a.status, a.notes]),
      [35, 10, 15, 40]
    ),
    spacer(),

    // ── Consistency Checks ──
    heading1("Consistency Checks"),
    simpleTable(
      ["Check", "Result", "Notes"],
      data.consistencyChecks.map((c) => [c.check, c.result, c.notes]),
      [35, 15, 50]
    ),
    spacer(),

    // ── Recommendations ──
    heading1("Recommendations"),
    ...data.recommendations.map((r) => bulletItem(r)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
