/**
 * Governance Structure Document Generator
 *
 * Converts a governance-structure artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateGovernanceStructure(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Governance Structure"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Decision Authority"),
    simpleTable(
      ["Decision Type", "Authority", "Threshold"],
      a(data.decisionAuthority).map((d: any) => [s(d?.decisionType), s(d?.authority), s(d?.threshold)]),
      [30, 30, 40]
    ),
    spacer(),

    heading1("Escalation Path"),
    simpleTable(
      ["Level", "Role", "Timeframe"],
      a(data.escalationPath).map((e: any) => [s(e?.level), s(e?.role), s(e?.timeframe)]),
      [30, 35, 35]
    ),
    spacer(),

    heading1("Recurring Meetings"),
    simpleTable(
      ["Meeting", "Frequency", "Attendees", "Purpose"],
      a(data.meetings).map((m: any) => [s(m?.name), s(m?.frequency), a(m?.attendees).join(", "), s(m?.purpose)]),
      [20, 15, 30, 35]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
