/**
 * Governance Structure Document Generator
 *
 * Converts a governance-structure artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface GovernanceStructureData {
  projectName: string;
  decisionAuthority: {
    decisionType: string;
    authority: string;
    threshold: string;
  }[];
  escalationPath: {
    level: string;
    role: string;
    timeframe: string;
  }[];
  meetings: {
    name: string;
    frequency: string;
    attendees: string[];
    purpose: string;
  }[];
}

export async function generateGovernanceStructure(data: GovernanceStructureData): Promise<Buffer> {
  const doc = createDocument([
    title("Governance Structure"),
    subtitle(data.projectName),
    spacer(),

    heading1("Decision Authority"),
    simpleTable(
      ["Decision Type", "Authority", "Threshold"],
      data.decisionAuthority.map((d) => [d.decisionType, d.authority, d.threshold]),
      [30, 30, 40]
    ),
    spacer(),

    heading1("Escalation Path"),
    simpleTable(
      ["Level", "Role", "Timeframe"],
      data.escalationPath.map((e) => [e.level, e.role, e.timeframe]),
      [30, 35, 35]
    ),
    spacer(),

    heading1("Recurring Meetings"),
    simpleTable(
      ["Meeting", "Frequency", "Attendees", "Purpose"],
      data.meetings.map((m) => [m.name, m.frequency, m.attendees.join(", "), m.purpose]),
      [20, 15, 30, 35]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
