/**
 * Kickoff Meeting Agenda Document Generator
 *
 * Converts a kickoff-agenda artifact (Stage 6) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  simpleTable,
  keyValueTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateKickoffAgenda(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Kickoff Meeting Agenda"),
    subtitle(s(data.projectName)),
    spacer(),

    // ── Meeting Details ──
    heading1("Meeting Details"),
    keyValueTable([
      { key: "Date", value: s(data.meetingDate) },
      { key: "Time", value: s(data.meetingTime) },
      { key: "Location", value: s(data.location) },
    ]),
    spacer(),

    // ── Attendees ──
    heading1("Attendees"),
    simpleTable(
      ["Name", "Role"],
      a(data.attendees).map((attendee: any) => [s(attendee?.name), s(attendee?.role)]),
      [40, 60]
    ),
    spacer(),

    // ── Agenda ──
    heading1("Agenda"),
    simpleTable(
      ["Topic", "Presenter", "Duration", "Description"],
      a(data.agendaItems).map((item: any) => [s(item?.topic), s(item?.presenter), s(item?.duration), s(item?.description)]),
      [25, 20, 12, 43]
    ),
    spacer(),

    // ── Pre-Read Materials ──
    heading1("Pre-Read Materials"),
    ...a(data.preReadMaterials).map((m: any) => bulletItem(s(m))),
    spacer(),

    // ── Action Items ──
    heading1("Post-Meeting Action Items"),
    ...a(data.actionItems).map((item: any) => bulletItem(s(item))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
