/**
 * Kickoff Meeting Agenda Document Generator
 *
 * Converts a kickoff-agenda artifact (Stage 6) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  simpleTable,
  keyValueTable,
  spacer,
  divider,
} from "./base-generator";

interface KickoffAgendaData {
  projectName: string;
  meetingDate: string;
  meetingTime: string;
  location: string;
  attendees: { name: string; role: string }[];
  agendaItems: {
    topic: string;
    presenter: string;
    duration: string;
    description: string;
  }[];
  preReadMaterials: string[];
  actionItems: string[];
}

export async function generateKickoffAgenda(data: KickoffAgendaData): Promise<Buffer> {
  const doc = createDocument([
    title("Kickoff Meeting Agenda"),
    subtitle(data.projectName),
    spacer(),

    // ── Meeting Details ──
    heading1("Meeting Details"),
    keyValueTable([
      { key: "Date", value: data.meetingDate },
      { key: "Time", value: data.meetingTime },
      { key: "Location", value: data.location },
    ]),
    spacer(),

    // ── Attendees ──
    heading1("Attendees"),
    simpleTable(
      ["Name", "Role"],
      data.attendees.map((a) => [a.name, a.role]),
      [40, 60]
    ),
    spacer(),

    // ── Agenda ──
    heading1("Agenda"),
    simpleTable(
      ["Topic", "Presenter", "Duration", "Description"],
      data.agendaItems.map((a) => [a.topic, a.presenter, a.duration, a.description]),
      [25, 20, 12, 43]
    ),
    spacer(),

    // ── Pre-Read Materials ──
    heading1("Pre-Read Materials"),
    ...data.preReadMaterials.map((m) => bulletItem(m)),
    spacer(),

    // ── Action Items ──
    heading1("Post-Meeting Action Items"),
    ...data.actionItems.map((a) => bulletItem(a)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
