/**
 * Project Classification Document Generator
 *
 * Converts a project-classification artifact (Stage 1) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  keyValueTable,
  spacer,
  divider,
} from "./base-generator";

interface ProjectClassificationData {
  projectName: string;
  projectType: string;
  industry: string;
  methodology: string;
  methodologyRationale: string;
  complexity: string;
  complexityFactors: {
    budget: string;
    timeline: string;
    teamSize: string;
    stakeholderCount: string;
  };
  keyCharacteristics: string[];
  recommendedArtifacts: string[];
}

export async function generateProjectClassification(data: ProjectClassificationData): Promise<Buffer> {
  const doc = createDocument([
    title("Project Classification"),
    subtitle(data.projectName),
    spacer(),

    heading1("Classification Summary"),
    keyValueTable([
      { key: "Project Type", value: data.projectType },
      { key: "Industry", value: data.industry },
      { key: "Methodology", value: data.methodology },
      { key: "Complexity", value: data.complexity },
    ]),
    spacer(),

    heading1("Methodology Rationale"),
    bodyText(data.methodologyRationale),
    spacer(),

    heading1("Complexity Factors"),
    keyValueTable([
      { key: "Budget", value: data.complexityFactors.budget },
      { key: "Timeline", value: data.complexityFactors.timeline },
      { key: "Team Size", value: data.complexityFactors.teamSize },
      { key: "Stakeholder Count", value: data.complexityFactors.stakeholderCount },
    ]),
    spacer(),

    heading1("Key Characteristics"),
    ...data.keyCharacteristics.map((c) => bulletItem(c)),
    spacer(),

    heading1("Recommended Artifacts"),
    ...data.recommendedArtifacts.map((a) => bulletItem(a)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
