/**
 * Project Brief Document Generator
 *
 * Converts a project-brief artifact (Stage 1) into a formatted Word document.
 * Uses the base generator for consistent styling.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  spacer,
  divider,
} from "./base-generator";

interface ProjectBriefData {
  projectName: string;
  projectSponsor: string;
  date: string;
  problemStatement: string;
  projectDescription: string;
  businessDrivers: string[];
  objectives: string[];
  estimatedBudget: string;
  estimatedTimeline: string;
  estimatedTeamSize: string;
  keyStakeholders: string[];
  initialRisks: string[];
  methodology: string;
  successCriteria: string[];
}

export async function generateProjectBrief(data: ProjectBriefData): Promise<Buffer> {
  const doc = createDocument([
    // ── Title Block ──
    title(`Project Brief`),
    subtitle(data.projectName),
    subtitle(`${data.date} • Sponsor: ${data.projectSponsor}`),
    spacer(),

    // ── Project Overview ──
    heading1("Project Overview"),
    keyValueTable([
      { key: "Project Name", value: data.projectName },
      { key: "Project Sponsor", value: data.projectSponsor },
      { key: "Date", value: data.date },
      { key: "Methodology", value: data.methodology },
    ]),
    spacer(),

    // ── Problem Statement ──
    heading1("Problem Statement"),
    bodyText(data.problemStatement),
    spacer(),

    // ── Project Description ──
    heading1("Project Description"),
    bodyText(data.projectDescription),
    spacer(),

    // ── Estimates ──
    heading1("Preliminary Estimates"),
    keyValueTable([
      { key: "Estimated Budget", value: data.estimatedBudget },
      { key: "Estimated Timeline", value: data.estimatedTimeline },
      { key: "Estimated Team Size", value: data.estimatedTeamSize },
    ]),
    spacer(),

    // ── Business Drivers ──
    heading1("Business Drivers"),
    ...data.businessDrivers.map((driver) => bulletItem(driver)),
    spacer(),

    // ── Objectives ──
    heading1("Project Objectives"),
    ...data.objectives.map((obj) => bulletItem(obj)),
    spacer(),

    // ── Key Stakeholders ──
    heading1("Key Stakeholders"),
    ...data.keyStakeholders.map((s) => bulletItem(s)),
    spacer(),

    // ── Initial Risks ──
    heading1("Initial Risks"),
    ...data.initialRisks.map((risk) => bulletItem(risk)),
    spacer(),

    // ── Success Criteria ──
    heading1("Success Criteria"),
    ...data.successCriteria.map((criterion) => bulletItem(criterion)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
