/**
 * Project Classification Document Generator
 *
 * Converts a project-classification artifact (Stage 1) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  keyValueTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateProjectClassification(data: any): Promise<Buffer> {
  const complexityFactors = data.complexityFactors ?? {};

  const doc = createDocument([
    title("Project Classification"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Classification Summary"),
    keyValueTable([
      { key: "Project Type", value: s(data.projectType) },
      { key: "Industry", value: s(data.industry) },
      { key: "Methodology", value: s(data.methodology) },
      { key: "Complexity", value: s(data.complexity) },
    ]),
    spacer(),

    heading1("Methodology Rationale"),
    bodyText(s(data.methodologyRationale)),
    spacer(),

    heading1("Complexity Factors"),
    keyValueTable([
      { key: "Budget", value: s(complexityFactors.budget) },
      { key: "Timeline", value: s(complexityFactors.timeline) },
      { key: "Team Size", value: s(complexityFactors.teamSize) },
      { key: "Stakeholder Count", value: s(complexityFactors.stakeholderCount) },
    ]),
    spacer(),

    heading1("Key Characteristics"),
    ...a(data.keyCharacteristics).map((c: any) => bulletItem(s(c))),
    spacer(),

    heading1("Recommended Artifacts"),
    ...a(data.recommendedArtifacts).map((artifact: any) => bulletItem(s(artifact))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
