/**
 * Project Brief Document Generator
 *
 * Converts a project-brief artifact (Stage 1) into a formatted Word document.
 * Uses the base generator for consistent styling.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateProjectBrief(data: any): Promise<Buffer> {
  const doc = createDocument([
    // ── Title Block ──
    title(`Project Brief`),
    subtitle(s(data.projectName)),
    subtitle(`${s(data.date)} • Sponsor: ${s(data.projectSponsor)}`),
    spacer(),

    // ── Project Overview ──
    heading1("Project Overview"),
    keyValueTable([
      { key: "Project Name", value: s(data.projectName) },
      { key: "Project Sponsor", value: s(data.projectSponsor) },
      { key: "Date", value: s(data.date) },
      { key: "Methodology", value: s(data.methodology) },
    ]),
    spacer(),

    // ── Problem Statement ──
    heading1("Problem Statement"),
    bodyText(s(data.problemStatement)),
    spacer(),

    // ── Project Description ──
    heading1("Project Description"),
    bodyText(s(data.projectDescription)),
    spacer(),

    // ── Estimates ──
    heading1("Preliminary Estimates"),
    keyValueTable([
      { key: "Estimated Budget", value: s(data.estimatedBudget) },
      { key: "Estimated Timeline", value: s(data.estimatedTimeline) },
      { key: "Estimated Team Size", value: s(data.estimatedTeamSize) },
    ]),
    spacer(),

    // ── Business Drivers ──
    heading1("Business Drivers"),
    ...a(data.businessDrivers).map((driver: any) => bulletItem(s(driver))),
    spacer(),

    // ── Objectives ──
    heading1("Project Objectives"),
    ...a(data.objectives).map((obj: any) => bulletItem(s(obj))),
    spacer(),

    // ── Key Stakeholders ──
    heading1("Key Stakeholders"),
    ...a(data.keyStakeholders).map((stakeholder: any) => bulletItem(s(stakeholder))),
    spacer(),

    // ── Initial Risks ──
    heading1("Initial Risks"),
    ...a(data.initialRisks).map((risk: any) => bulletItem(s(risk))),
    spacer(),

    // ── Success Criteria ──
    heading1("Success Criteria"),
    ...a(data.successCriteria).map((criterion: any) => bulletItem(s(criterion))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
