/**
 * Quality Management Plan Document Generator
 *
 * Converts a quality-plan artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface QualityPlanData {
  projectName: string;
  qualityObjectives: string[];
  standards: {
    deliverable: string;
    qualityStandard: string;
    acceptanceCriteria: string;
    reviewProcess: string;
    reviewer: string;
  }[];
  qualityMetrics: {
    metric: string;
    target: string;
    measurementMethod: string;
    frequency: string;
  }[];
  continuousImprovement: string;
}

export async function generateQualityPlan(data: QualityPlanData): Promise<Buffer> {
  const doc = createDocument([
    title("Quality Management Plan"),
    subtitle(data.projectName),
    spacer(),

    heading1("Quality Objectives"),
    ...data.qualityObjectives.map((o) => bulletItem(o)),
    spacer(),

    heading1("Quality Standards"),
    simpleTable(
      ["Deliverable", "Quality Standard", "Acceptance Criteria", "Review Process", "Reviewer"],
      data.standards.map((s) => [
        s.deliverable,
        s.qualityStandard,
        s.acceptanceCriteria,
        s.reviewProcess,
        s.reviewer,
      ]),
      [18, 22, 22, 20, 18]
    ),
    spacer(),

    heading1("Quality Metrics"),
    simpleTable(
      ["Metric", "Target", "Measurement Method", "Frequency"],
      data.qualityMetrics.map((m) => [m.metric, m.target, m.measurementMethod, m.frequency]),
      [25, 25, 30, 20]
    ),
    spacer(),

    heading1("Continuous Improvement"),
    bodyText(data.continuousImprovement),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
