/**
 * Quality Management Plan Document Generator
 *
 * Converts a quality-plan artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateQualityPlan(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Quality Management Plan"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Quality Objectives"),
    ...a(data.qualityObjectives).map((o: any) => bulletItem(s(o))),
    spacer(),

    heading1("Quality Standards"),
    simpleTable(
      ["Deliverable", "Quality Standard", "Acceptance Criteria", "Review Process", "Reviewer"],
      a(data.standards).map((standard: any) => [
        s(standard?.deliverable),
        s(standard?.qualityStandard),
        s(standard?.acceptanceCriteria),
        s(standard?.reviewProcess),
        s(standard?.reviewer),
      ]),
      [18, 22, 22, 20, 18]
    ),
    spacer(),

    heading1("Quality Metrics"),
    simpleTable(
      ["Metric", "Target", "Measurement Method", "Frequency"],
      a(data.qualityMetrics).map((m: any) => [s(m?.metric), s(m?.target), s(m?.measurementMethod), s(m?.frequency)]),
      [25, 25, 30, 20]
    ),
    spacer(),

    heading1("Continuous Improvement"),
    bodyText(s(data.continuousImprovement)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
