/**
 * RACI Matrix Document Generator
 *
 * Converts a raci-matrix artifact (Stage 4) into a formatted Word document.
 * Creates a proper matrix with deliverables as rows and roles as columns.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateRaciMatrix(data: any): Promise<Buffer> {
  const roles = a(data.roles);

  // Build the matrix: first column is deliverable, remaining columns are roles
  const headers = ["Deliverable", ...roles.map((r: any) => s(r))];
  const widths = [30, ...roles.map(() => Math.floor(70 / Math.max(roles.length, 1)))];

  const rows = a(data.items).map((item: any) => {
    const row = [s(item?.deliverable)];
    for (const role of roles) {
      const assignment = a<any>(item?.assignments).find((assign: any) => assign?.role === role);
      row.push(s(assignment?.type));
    }
    return row;
  });

  const doc = createDocument([
    title("RACI Matrix"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Responsibility Assignment Matrix"),
    bodyText("R = Responsible (does the work) | A = Accountable (approves) | C = Consulted | I = Informed"),
    spacer(),

    simpleTable(headers, rows, widths),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
