/**
 * RACI Matrix Document Generator
 *
 * Converts a raci-matrix artifact (Stage 4) into a formatted Word document.
 * Creates a proper matrix with deliverables as rows and roles as columns.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface RaciMatrixData {
  projectName: string;
  roles: string[];
  items: {
    deliverable: string;
    assignments: { role: string; type: string }[];
  }[];
}

export async function generateRaciMatrix(data: RaciMatrixData): Promise<Buffer> {
  // Build the matrix: first column is deliverable, remaining columns are roles
  const headers = ["Deliverable", ...data.roles];
  const colCount = headers.length;
  const widths = [30, ...data.roles.map(() => Math.floor(70 / data.roles.length))];

  const rows = data.items.map((item) => {
    const row = [item.deliverable];
    for (const role of data.roles) {
      const assignment = item.assignments.find((a) => a.role === role);
      row.push(assignment?.type ?? "");
    }
    return row;
  });

  const doc = createDocument([
    title("RACI Matrix"),
    subtitle(data.projectName),
    spacer(),

    heading1("Responsibility Assignment Matrix"),
    bodyText("R = Responsible (does the work) | A = Accountable (approves) | C = Consulted | I = Informed"),
    spacer(),

    simpleTable(headers, rows, widths),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
