/**
 * Resource Plan Document Generator
 *
 * Converts a resource-plan artifact (Stage 3) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  labeledField,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateResourcePlan(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Resource Plan"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Team Roles"),
    simpleTable(
      ["Role", "Description", "Skills", "Allocation", "Duration", "Source", "Cost"],
      a(data.roles).map((r: any) => [
        s(r?.role),
        s(r?.description),
        a(r?.skills).join(", "),
        s(r?.allocation),
        s(r?.duration),
        s(r?.source),
        s(r?.estimatedCost),
      ]),
      [13, 18, 18, 10, 12, 12, 12]
    ),
    spacer(),

    heading1("Summary"),
    labeledField("Total Headcount", s(data.totalHeadcount)),
    spacer(),

    heading1("Sourcing Notes"),
    bodyText(s(data.sourcingNotes)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
