/**
 * Resource Plan Document Generator
 *
 * Converts a resource-plan artifact (Stage 3) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  labeledField,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface ResourcePlanData {
  projectName: string;
  roles: {
    role: string;
    description: string;
    skills: string[];
    allocation: string;
    duration: string;
    source: string;
    estimatedCost: string;
  }[];
  totalHeadcount: string;
  sourcingNotes: string;
}

export async function generateResourcePlan(data: ResourcePlanData): Promise<Buffer> {
  const doc = createDocument([
    title("Resource Plan"),
    subtitle(data.projectName),
    spacer(),

    heading1("Team Roles"),
    simpleTable(
      ["Role", "Description", "Skills", "Allocation", "Duration", "Source", "Cost"],
      data.roles.map((r) => [
        r.role,
        r.description,
        r.skills.join(", "),
        r.allocation,
        r.duration,
        r.source,
        r.estimatedCost,
      ]),
      [13, 18, 18, 10, 12, 12, 12]
    ),
    spacer(),

    heading1("Summary"),
    labeledField("Total Headcount", data.totalHeadcount),
    spacer(),

    heading1("Sourcing Notes"),
    bodyText(data.sourcingNotes),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
