/**
 * Risk Register Document Generator
 *
 * Converts a risk-register artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateRiskRegister(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Risk Register"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Risk Assessment"),
    simpleTable(
      ["ID", "Category", "Description", "P", "I", "Score", "Rating", "Mitigation", "Contingency", "Owner", "Status"],
      a(data.risks).map((r: any) => [
        s(r?.id),
        s(r?.category),
        s(r?.description),
        String(r?.probability ?? ""),
        String(r?.impact ?? ""),
        String(r?.score ?? ""),
        s(r?.rating),
        s(r?.mitigation),
        s(r?.contingency),
        s(r?.owner),
        s(r?.status),
      ]),
      [5, 8, 14, 4, 4, 5, 7, 17, 14, 10, 7]
    ),
    spacer(),

    bodyText("P = Probability (1-5), I = Impact (1-5), Score = P x I", { italic: true }),
    bodyText("Rating: Low (1-4), Medium (5-9), High (10-15), Critical (16-25)", { italic: true }),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
