/**
 * Risk Register Document Generator
 *
 * Converts a risk-register artifact (Stage 5) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface RiskRegisterData {
  projectName: string;
  risks: {
    id: string;
    category: string;
    description: string;
    probability: number;
    impact: number;
    score: number;
    rating: string;
    mitigation: string;
    contingency: string;
    owner: string;
    status: string;
  }[];
}

export async function generateRiskRegister(data: RiskRegisterData): Promise<Buffer> {
  const doc = createDocument([
    title("Risk Register"),
    subtitle(data.projectName),
    spacer(),

    heading1("Risk Assessment"),
    simpleTable(
      ["ID", "Category", "Description", "P", "I", "Score", "Rating", "Mitigation", "Contingency", "Owner", "Status"],
      data.risks.map((r) => [
        r.id,
        r.category,
        r.description,
        String(r.probability),
        String(r.impact),
        String(r.score),
        r.rating,
        r.mitigation,
        r.contingency,
        r.owner,
        r.status,
      ]),
      [5, 8, 14, 4, 4, 5, 7, 17, 14, 10, 7]
    ),
    spacer(),

    bodyText("P = Probability (1-5), I = Impact (1-5), Score = P x I", { italic: true }),
    bodyText("Rating: Low (1-4), Medium (5-9), High (10-15), Critical (16-25)", { italic: true }),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
