/**
 * Project Schedule Document Generator
 *
 * Converts a schedule artifact (Stage 3) into a formatted Word document.
 */
import { Paragraph, Table } from "docx";
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface ScheduleData {
  projectName: string;
  startDate: string;
  endDate: string;
  phases: {
    name: string;
    startDate: string;
    endDate: string;
    milestones: { name: string; date: string }[];
    dependencies: string[];
    keyDeliverables: string[];
  }[];
  criticalPath: string[];
}

export async function generateSchedule(data: ScheduleData): Promise<Buffer> {
  const content: (Paragraph | Table)[] = [
    title("Project Schedule"),
    subtitle(data.projectName),
    spacer(),

    labeledField("Project Start", data.startDate),
    labeledField("Project End", data.endDate),
    spacer(),
  ];

  // Phase details
  for (const phase of data.phases) {
    content.push(heading1(phase.name));
    content.push(labeledField("Start", phase.startDate));
    content.push(labeledField("End", phase.endDate));

    if (phase.milestones.length > 0) {
      content.push(heading2("Milestones"));
      content.push(
        simpleTable(
          ["Milestone", "Target Date"],
          phase.milestones.map((m) => [m.name, m.date]),
          [60, 40]
        )
      );
    }

    if (phase.dependencies.length > 0) {
      content.push(heading2("Dependencies"));
      for (const dep of phase.dependencies) {
        content.push(bulletItem(dep));
      }
    }

    if (phase.keyDeliverables.length > 0) {
      content.push(heading2("Key Deliverables"));
      for (const del of phase.keyDeliverables) {
        content.push(bulletItem(del));
      }
    }

    content.push(spacer());
  }

  // Critical Path
  if (data.criticalPath.length > 0) {
    content.push(heading1("Critical Path"));
    for (const item of data.criticalPath) {
      content.push(bulletItem(item));
    }
  }

  content.push(divider());
  content.push(bodyText("This document was generated by BriefKit.", { italic: true }));

  const doc = createDocument(content);
  return Buffer.from(await Packer.toBuffer(doc));
}
