/**
 * Scope Statement Document Generator
 *
 * Converts a scope-statement artifact (Stage 2) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface ScopeStatementData {
  projectName: string;
  projectObjective: string;
  inScope: { item: string; description: string }[];
  outOfScope: { item: string; rationale: string }[];
  deliverables: { deliverable: string; description: string; acceptanceCriteria: string }[];
  assumptions: string[];
  constraints: string[];
}

export async function generateScopeStatement(data: ScopeStatementData): Promise<Buffer> {
  const doc = createDocument([
    title("Scope Statement"),
    subtitle(data.projectName),
    spacer(),

    // ── Project Objective ──
    heading1("Project Objective"),
    bodyText(data.projectObjective),
    spacer(),

    // ── In Scope ──
    heading1("In Scope"),
    simpleTable(
      ["Item", "Description"],
      data.inScope.map((s) => [s.item, s.description]),
      [30, 70]
    ),
    spacer(),

    // ── Out of Scope ──
    heading1("Out of Scope"),
    simpleTable(
      ["Item", "Rationale"],
      data.outOfScope.map((s) => [s.item, s.rationale]),
      [30, 70]
    ),
    spacer(),

    // ── Deliverables ──
    heading1("Deliverables"),
    simpleTable(
      ["Deliverable", "Description", "Acceptance Criteria"],
      data.deliverables.map((d) => [d.deliverable, d.description, d.acceptanceCriteria]),
      [25, 40, 35]
    ),
    spacer(),

    // ── Assumptions ──
    heading1("Assumptions"),
    ...data.assumptions.map((a) => bulletItem(a)),
    spacer(),

    // ── Constraints ──
    heading1("Constraints"),
    ...data.constraints.map((c) => bulletItem(c)),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
