/**
 * Scope Statement Document Generator
 *
 * Converts a scope-statement artifact (Stage 2) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  bulletItem,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateScopeStatement(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Scope Statement"),
    subtitle(s(data.projectName)),
    spacer(),

    // ── Project Objective ──
    heading1("Project Objective"),
    bodyText(s(data.projectObjective)),
    spacer(),

    // ── In Scope ──
    heading1("In Scope"),
    simpleTable(
      ["Item", "Description"],
      a(data.inScope).map((item: any) => [s(item?.item), s(item?.description)]),
      [30, 70]
    ),
    spacer(),

    // ── Out of Scope ──
    heading1("Out of Scope"),
    simpleTable(
      ["Item", "Rationale"],
      a(data.outOfScope).map((item: any) => [s(item?.item), s(item?.rationale)]),
      [30, 70]
    ),
    spacer(),

    // ── Deliverables ──
    heading1("Deliverables"),
    simpleTable(
      ["Deliverable", "Description", "Acceptance Criteria"],
      a(data.deliverables).map((d: any) => [s(d?.deliverable), s(d?.description), s(d?.acceptanceCriteria)]),
      [25, 40, 35]
    ),
    spacer(),

    // ── Assumptions ──
    heading1("Assumptions"),
    ...a(data.assumptions).map((assumption: any) => bulletItem(s(assumption))),
    spacer(),

    // ── Constraints ──
    heading1("Constraints"),
    ...a(data.constraints).map((constraint: any) => bulletItem(s(constraint))),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
