/**
 * Statement of Work / Project Initiation Document Generator
 *
 * Converts a sow-pid artifact (Stage 6) into a formatted Word document.
 * This is the master document that pulls content from all prior stages.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateSowPid(data: any): Promise<Buffer> {
  const scopeSummary = data.scopeSummary ?? {};
  const scheduleSummary = data.scheduleSummary ?? {};
  const budgetSummary = data.budgetSummary ?? {};

  const doc = createDocument([
    title("Statement of Work / Project Initiation Document"),
    subtitle(s(data.projectName)),
    subtitle(`Version ${s(data.version)} — ${s(data.date)}`),
    spacer(),

    // ── Executive Summary ──
    heading1("1. Executive Summary"),
    bodyText(s(data.executiveSummary)),
    spacer(),

    // ── Objectives ──
    heading1("2. Project Objectives"),
    ...a(data.objectives).map((o: any) => bulletItem(s(o))),
    spacer(),

    // ── Scope ──
    heading1("3. Scope Summary"),
    heading2("In Scope"),
    ...a(scopeSummary.inScope).map((item: any) => bulletItem(s(item))),
    heading2("Out of Scope"),
    ...a(scopeSummary.outOfScope).map((item: any) => bulletItem(s(item))),
    spacer(),

    // ── WBS ──
    heading1("4. Work Breakdown Summary"),
    ...a(data.wbsSummary).map((w: any) => bulletItem(s(w))),
    spacer(),

    // ── Schedule ──
    heading1("5. Schedule Overview"),
    labeledField("Start Date", s(scheduleSummary.startDate)),
    labeledField("End Date", s(scheduleSummary.endDate)),
    spacer(),
    heading2("Key Milestones"),
    simpleTable(
      ["Milestone", "Date"],
      a(scheduleSummary.keyMilestones).map((m: any) => [s(m?.milestone), s(m?.date)]),
      [60, 40]
    ),
    spacer(),

    // ── Budget ──
    heading1("6. Budget Summary"),
    keyValueTable([
      { key: "Total Budget", value: s(budgetSummary.totalBudget) },
      { key: "Contingency", value: s(budgetSummary.contingency) },
    ]),
    spacer(),

    // ── Team ──
    heading1("7. Team Summary"),
    ...a(data.teamSummary).map((t: any) => bulletItem(s(t))),
    spacer(),

    // ── Governance ──
    heading1("8. Governance"),
    bodyText(s(data.governanceSummary)),
    spacer(),

    // ── Top Risks ──
    heading1("9. Top Risks"),
    simpleTable(
      ["Risk", "Rating", "Mitigation"],
      a(data.topRisks).map((r: any) => [s(r?.risk), s(r?.rating), s(r?.mitigation)]),
      [35, 15, 50]
    ),
    spacer(),

    // ── Quality ──
    heading1("10. Quality Approach"),
    bodyText(s(data.qualityApproach)),
    spacer(),

    // ── Approvals ──
    heading1("11. Approvals"),
    simpleTable(
      ["Name", "Role", "Signature", "Date"],
      a(data.approvals).map((approval: any) => [s(approval?.name), s(approval?.role), "", s(approval?.date)]),
      [25, 25, 30, 20]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
