/**
 * Statement of Work / Project Initiation Document Generator
 *
 * Converts a sow-pid artifact (Stage 6) into a formatted Word document.
 * This is the master document that pulls content from all prior stages.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  bulletItem,
  keyValueTable,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface SowPidData {
  projectName: string;
  version: string;
  date: string;
  executiveSummary: string;
  objectives: string[];
  scopeSummary: { inScope: string[]; outOfScope: string[] };
  wbsSummary: string[];
  scheduleSummary: {
    startDate: string;
    endDate: string;
    keyMilestones: { milestone: string; date: string }[];
  };
  budgetSummary: { totalBudget: string; contingency: string };
  teamSummary: string[];
  governanceSummary: string;
  topRisks: { risk: string; rating: string; mitigation: string }[];
  qualityApproach: string;
  approvals: { name: string; role: string; date: string }[];
}

export async function generateSowPid(data: SowPidData): Promise<Buffer> {
  const doc = createDocument([
    title("Statement of Work / Project Initiation Document"),
    subtitle(data.projectName),
    subtitle(`Version ${data.version} — ${data.date}`),
    spacer(),

    // ── Executive Summary ──
    heading1("1. Executive Summary"),
    bodyText(data.executiveSummary),
    spacer(),

    // ── Objectives ──
    heading1("2. Project Objectives"),
    ...data.objectives.map((o) => bulletItem(o)),
    spacer(),

    // ── Scope ──
    heading1("3. Scope Summary"),
    heading2("In Scope"),
    ...data.scopeSummary.inScope.map((s) => bulletItem(s)),
    heading2("Out of Scope"),
    ...data.scopeSummary.outOfScope.map((s) => bulletItem(s)),
    spacer(),

    // ── WBS ──
    heading1("4. Work Breakdown Summary"),
    ...data.wbsSummary.map((w) => bulletItem(w)),
    spacer(),

    // ── Schedule ──
    heading1("5. Schedule Overview"),
    labeledField("Start Date", data.scheduleSummary.startDate),
    labeledField("End Date", data.scheduleSummary.endDate),
    spacer(),
    heading2("Key Milestones"),
    simpleTable(
      ["Milestone", "Date"],
      data.scheduleSummary.keyMilestones.map((m) => [m.milestone, m.date]),
      [60, 40]
    ),
    spacer(),

    // ── Budget ──
    heading1("6. Budget Summary"),
    keyValueTable([
      { key: "Total Budget", value: data.budgetSummary.totalBudget },
      { key: "Contingency", value: data.budgetSummary.contingency },
    ]),
    spacer(),

    // ── Team ──
    heading1("7. Team Summary"),
    ...data.teamSummary.map((t) => bulletItem(t)),
    spacer(),

    // ── Governance ──
    heading1("8. Governance"),
    bodyText(data.governanceSummary),
    spacer(),

    // ── Top Risks ──
    heading1("9. Top Risks"),
    simpleTable(
      ["Risk", "Rating", "Mitigation"],
      data.topRisks.map((r) => [r.risk, r.rating, r.mitigation]),
      [35, 15, 50]
    ),
    spacer(),

    // ── Quality ──
    heading1("10. Quality Approach"),
    bodyText(data.qualityApproach),
    spacer(),

    // ── Approvals ──
    heading1("11. Approvals"),
    simpleTable(
      ["Name", "Role", "Signature", "Date"],
      data.approvals.map((a) => [a.name, a.role, "", a.date]),
      [25, 25, 30, 20]
    ),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
