/**
 * Stakeholder Register Document Generator
 *
 * Converts a stakeholder-register artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface StakeholderRegisterData {
  projectName: string;
  stakeholders: {
    name: string;
    role: string;
    organization: string;
    power: string;
    interest: string;
    classification: string;
    attitude: string;
    engagementStrategy: string;
  }[];
}

export async function generateStakeholderRegister(data: StakeholderRegisterData): Promise<Buffer> {
  const doc = createDocument([
    title("Stakeholder Register"),
    subtitle(data.projectName),
    spacer(),

    heading1("Stakeholder Analysis"),
    simpleTable(
      ["Name", "Role", "Organization", "Power", "Interest", "Classification", "Attitude", "Engagement Strategy"],
      data.stakeholders.map((s) => [
        s.name,
        s.role,
        s.organization,
        s.power,
        s.interest,
        s.classification,
        s.attitude,
        s.engagementStrategy,
      ]),
      [12, 12, 12, 8, 8, 14, 10, 24]
    ),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
