/**
 * Stakeholder Register Document Generator
 *
 * Converts a stakeholder-register artifact (Stage 4) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  bodyText,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateStakeholderRegister(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Stakeholder Register"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Stakeholder Analysis"),
    simpleTable(
      ["Name", "Role", "Organization", "Power", "Interest", "Classification", "Attitude", "Engagement Strategy"],
      a(data.stakeholders).map((stakeholder: any) => [
        s(stakeholder?.name),
        s(stakeholder?.role),
        s(stakeholder?.organization),
        s(stakeholder?.power),
        s(stakeholder?.interest),
        s(stakeholder?.classification),
        s(stakeholder?.attitude),
        s(stakeholder?.engagementStrategy),
      ]),
      [12, 12, 12, 8, 8, 14, 10, 24]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
