/**
 * Success Criteria & KPIs Document Generator
 *
 * Converts a success-criteria artifact (Stage 2) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  simpleTable,
  spacer,
  divider,
  bodyText,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateSuccessCriteria(data: any): Promise<Buffer> {
  const doc = createDocument([
    title("Success Criteria & KPIs"),
    subtitle(s(data.projectName)),
    spacer(),

    heading1("Key Performance Indicators"),
    simpleTable(
      ["KPI", "Description", "Baseline", "Target", "Measurement", "Frequency"],
      a(data.kpis).map((k: any) => [
        s(k?.name),
        s(k?.description),
        s(k?.baseline),
        s(k?.target),
        s(k?.measurementMethod),
        s(k?.frequency),
      ]),
      [15, 25, 12, 12, 20, 16]
    ),

    divider(),
    bodyText("This document was generated by BriefKit.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
