/**
 * Success Criteria & KPIs Document Generator
 *
 * Converts a success-criteria artifact (Stage 2) into a formatted Word document.
 */
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  simpleTable,
  spacer,
  divider,
  bodyText,
} from "./base-generator";

interface SuccessCriteriaData {
  projectName: string;
  kpis: {
    name: string;
    description: string;
    baseline: string;
    target: string;
    measurementMethod: string;
    frequency: string;
  }[];
}

export async function generateSuccessCriteria(data: SuccessCriteriaData): Promise<Buffer> {
  const doc = createDocument([
    title("Success Criteria & KPIs"),
    subtitle(data.projectName),
    spacer(),

    heading1("Key Performance Indicators"),
    simpleTable(
      ["KPI", "Description", "Baseline", "Target", "Measurement", "Frequency"],
      data.kpis.map((k) => [
        k.name,
        k.description,
        k.baseline,
        k.target,
        k.measurementMethod,
        k.frequency,
      ]),
      [15, 25, 12, 12, 20, 16]
    ),

    divider(),
    bodyText("This document was generated by Brief-to-Project.", { italic: true }),
  ]);

  return Buffer.from(await Packer.toBuffer(doc));
}
