/**
 * Work Breakdown Structure (WBS) Document Generator
 *
 * Converts a wbs artifact (Stage 3) into a formatted Word document.
 * Uses indentation and numbering to show the hierarchy.
 */
import { Paragraph, Table } from "docx";
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  simpleTable,
  spacer,
  divider,
} from "./base-generator";

interface WbsData {
  projectName: string;
  methodology: string;
  deliverables: {
    id: string;
    name: string;
    workPackages: {
      id: string;
      name: string;
      tasks: {
        id: string;
        name: string;
        estimatedEffort: string;
        estimatedDuration: string;
        owner: string;
      }[];
    }[];
  }[];
}

export async function generateWbs(data: WbsData): Promise<Buffer> {
  const content: (Paragraph | Table)[] = [
    title("Work Breakdown Structure"),
    subtitle(data.projectName),
    spacer(),

    labeledField("Methodology", data.methodology),
    spacer(),
  ];

  // Build the hierarchical WBS
  for (const deliverable of data.deliverables) {
    content.push(heading1(`${deliverable.id} ${deliverable.name}`));

    for (const wp of deliverable.workPackages) {
      content.push(heading2(`${wp.id} ${wp.name}`));

      if (wp.tasks.length > 0) {
        content.push(
          simpleTable(
            ["ID", "Task", "Effort", "Duration", "Owner"],
            wp.tasks.map((t) => [
              t.id,
              t.name,
              t.estimatedEffort,
              t.estimatedDuration,
              t.owner,
            ]),
            [10, 35, 15, 20, 20]
          )
        );
        content.push(spacer());
      }
    }
  }

  content.push(divider());
  content.push(bodyText("This document was generated by BriefKit.", { italic: true }));

  const doc = createDocument(content);
  return Buffer.from(await Packer.toBuffer(doc));
}
