/**
 * Work Breakdown Structure (WBS) Document Generator
 *
 * Converts a wbs artifact (Stage 3) into a formatted Word document.
 * Uses indentation and numbering to show the hierarchy.
 */
import { Paragraph, Table } from "docx";
import {
  createDocument,
  Packer,
  title,
  subtitle,
  heading1,
  heading2,
  bodyText,
  labeledField,
  simpleTable,
  spacer,
  divider,
  s,
  a,
} from "./base-generator";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function generateWbs(data: any): Promise<Buffer> {
  const content: (Paragraph | Table)[] = [
    title("Work Breakdown Structure"),
    subtitle(s(data.projectName)),
    spacer(),

    labeledField("Methodology", s(data.methodology)),
    spacer(),
  ];

  // Build the hierarchical WBS
  for (const deliverable of a<any>(data.deliverables)) {
    content.push(heading1(`${s(deliverable?.id)} ${s(deliverable?.name)}`));

    for (const wp of a<any>(deliverable?.workPackages)) {
      content.push(heading2(`${s(wp?.id)} ${s(wp?.name)}`));

      if (a<any>(wp?.tasks).length > 0) {
        content.push(
          simpleTable(
            ["ID", "Task", "Effort", "Duration", "Owner"],
            a<any>(wp?.tasks).map((t: any) => [
              s(t?.id),
              s(t?.name),
              s(t?.estimatedEffort),
              s(t?.estimatedDuration),
              s(t?.owner),
            ]),
            [10, 35, 15, 20, 20]
          )
        );
        content.push(spacer());
      }
    }
  }

  content.push(divider());
  content.push(bodyText("This document was generated by BriefKit.", { italic: true }));

  const doc = createDocument(content);
  return Buffer.from(await Packer.toBuffer(doc));
}
